### ISSUE TITLE
Use with lecroy scope

### ISSUE THREAD

**Issue by saonim** [python-ivi/python-ivi#56]
Hi, 

I am trying to control my lecroy WR640Zi scope remotely with ivi. Earlier I have used this package with an agilent one and it was a breeze! However with the lecroy, there is very small to no documentation on how I can set up the mso. Earlier it was like:
ivi.agilent.agilentMSOX4104A("TCPIP0::<x.x.x.x>::INSTR"). So for the new one, since I could not find the exact model, I tried:
mso = ivi.lecroy.lecroyWR64MXIA("TCPIP0::<y.y.y.y>::inst0::INSTR")

However this threw an error:

Traceback (most recent call last):
  File "power_py.py", line 11, in <module>
    mso = ivi.lecroy.lecroyWR64MXIA("TCPIP0::<y.y.y.y>::inst0::INSTR")
  File "/usr/local/lib/python2.7/dist-packages/python_ivi-0.14.9-py2.7.egg/ivi/lecroy/lecroyWR64MXIA.py", line 35, in __init__
    super(lecroy104MXiA, self).__init__(*args, **kwargs)
NameError: global name 'lecroy104MXiA' is not defined

**Comment by rmax7** [comment]
Looks like it is because of the typo in the original file. First of all, there is no class as lecroy104MXIA, it should be super(lecroy**WR**104MXIA).init(*args, **kwargs)

But even if you correct the typo, I think it should have been:
super(lecroyWR**64**MXIA).init(*args, **kwargs). 

By the way, it should be fixed in /usr/local/lib/.... path that is mentioned in your question. Just saying so that you don't change it in some local extracted copy and expect it to work. Done that before :-)
